# cargo make build
[tasks.build]
command = "echo"
dependencies = ["build-node", "build-web"]

[tasks.build-node]
command = "wasm-pack"
args = ["build", "--target", "nodejs", "--out-dir", "node"]

[tasks.build-web]
command = "wasm-pack"
args = ["build", "--target", "browser", "--out-dir", "pkg"]
